# Generated by Django 6.0.2 on 2026-02-19 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bom',
            old_name='finished_product',
            new_name='ready_product',
        ),
        migrations.RenameField(
            model_name='bomline',
            old_name='component',
            new_name='ingridient',
        ),
        migrations.RenameField(
            model_name='manufacturingorder',
            old_name='quantity_to_produce',
            new_name='producing_quantity',
        ),
        migrations.RemoveField(
            model_name='manufacturingorder',
            name='created_at',
        ),
    ]
